flags: {}
extra-package-dbs: []
ghc-options:
  ! '*': -O1
packages:
- '.'
- location:
    git: https://github.com/acowley/Frames.git
    commit: cd6367c4ed413c265eff51de57dbefa19c0cbc2e
  extra-dep: true
- location:
    git: https://github.com/codygman/frames-diff.git
    commit: 1546609f7d6fa26c2b2d014036b5f57dc5d0671f
  extra-dep: true
extra-deps:
- tz-0.1.2.0
resolver: lts-7.14
